__all__ = ["test_bootstrap",
           "test_bootstrap_workers",
           "test_curve_fitting",
           "test_cyth",
           "test_kde",
           "test_kernel_smoothing",
           "test_kernels",
           "test_loader",
           "test_plot_fit",
           "test_pyqt_fit1d",
           "test_sharedmem",
           "test_utils"]
